layout_spectrum: 0.06272799335420132
typography_spectrum: 0.9444341456983238
color:
  brandStrength: 0.044897336745634675
  lightness: 0.65101553266868
  saturation: 0.5599633892998099
  rhythmicContrast: 0.1097283880226314
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
name: Kālī Brewery
